name: Build and Publish Release (Main)

on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Build and package with pkg
      run: |
        npm install -g pkg
        npm run pkg

    - name: Create or update release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: continuous-release-main
        release_name: Continuous Release (Main)
        draft: false
        prerelease: true

    - name: Upload binaries to release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
        release_id: ${{ steps.create_release.outputs.id }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
